assets/events-db/events-db.json
assets/js/events.js
events.html

**Description :**
- Create database json file with keys and values, they need to be discussed with Kamil for the contact form.
- Create event.js file that reads event-db.json and displays values in .container in events.html
- Depends on odd or even event count, events.html formats text and pictures the opposite way than previous event
- JS tested and validated

Create data handler for events JSON file

---

assets/css/styles.css

Added css to "main" div, padding top

Added padding top to main

---

about.html
assets/css/styles.css
index.html

Created basic templates for index and about pages

Basic Styling for Home and About page

---

assets/js/events.js

*Description : *
- no changes made to program
- comments added

Add comments to events.js

---

README.md
about.html
assets/css/styles.css
contactBusiness.html
contactUser.html
events.html
gallery.html

Change 'active' classes. CSS for navbar on About page. Add live site web to README for easy access (for now).

Work on CSS on About page

---

about.html
assets/css/styles.css

Edit 'About' page CSS. Fix BUG in logo url.

About CSS. Fix logo url.

---

assets/css/styles.css
assets/events-db/events-db.json
assets/js/events.js
events.html

*Description :*
- Add map to events page
- Based on event locations, maps displays pins
- Based on event category, pins do have different colors
- Colors of cards with events do match the color of map pins

Add map pins for events

---

assets/js/events.js

- initMap() was disabled for testing
- all testing done now

Uncomment  initMap() in events.js

---

assets/css/styles.css

- style.css was missing } after yesterday's merge conflict
- all sorted now

Fix bug with css file

---

README.md

Add some CSS tools used to README.md file

Add some CSS tools used to README.md file

---

about.html
assets/css/styles.css
events.html

-Add logo and favicon to About page. 
-Test style CSS for About page.

Work on CSS for About page

---

assets/css/styles.css
contactUser.html
index.html

Changed Recommendation spelling on user contact form, styled index.html

Neils branch

---

index.html

Styled index.html to match about page

Styled Header to match events.html

---

index.html

Set index.html to active in navbar

Set index.html to active in navbar

---

contactUser.html

Changed Recommendations value to match Recommendations

Changed Recommendations value to match Recommendations

---

assets/css/styles.css
index.html

CSS stylinh index.html

---

assets/css/styles.css
index.html

Styled index.html

---

assets/css/styles.css
index.html

Changed card colour for carousel

Altered CSS background for carousel

---

assets/css/styles.css
index.html

Added trial colour option to index.html

Added CSS color to index.html

---

gallery.html

Styled Gallery images

---

assets/css/styles.css

Aligned info text on index.html

Alligned text on index.html

---

assets/css/styles.css

Added nav border bottom in css

Added border-bottom to nav

---

assets/css/styles.css

Changed background colour on Gallery tiles

---

assets/css/styles.css
contactBusiness.html
gallery.html

Merge conflict troubleshooting

Merge conflict troubleshooting

---

assets/css/styles.css

Add black border under navbar

---

assets/css/styles.css
contactBusiness.html
contactUser.html
gallery.html

Finish media queries. Clean up CSS file.

Finish media queries. Clean up CSS file.

---

assets/css/styles.css

Troubleshooting styles.css

---

assets/css/styles.css

Take away line in footer

---

zoom.html

Edit footer on zoom.html to match rest of pages.

Footer zoom.html

---

404.html
about.html
assets/css/styles.css
contactBusiness.html
contactUser.html
devs.html
events.html
gallery.html
index.html
zoom.html

Add styling and trademark symbol

Styled footer content

---

assets/css/styles.css

Underlined trademark at bottom of footer

Styling trademark

---

index.html

Changed font size for anchors in footer

Changed font size for footer links

---

assets/css/styles.css
assets/js/events.js
events.html

responsive styling events.html

---

assets/events-db/events-db.json

new events design

---

assets/js/zoom.js

Rearranged pictures array in zoom.js and tested site - order matches up

Rearranged pictures array in zoom.js

---

404.html
assets/css/styles.css

Styled 404.html and CSS for 404 page

Styled 404.html

---

assets/events-db/events-db.json

update on events page pt2

---

zoom.html

Changed icons on zoom.html to filled arrows

Changed icons for zoom.html arrows

---

zoom.html

Add missing navbar class on zoom.html

Add missing navbar class on zoom.html

---

assets/css/styles.css

Add map legend media query

---

assets/css/styles.css

Clean up css (delete commented out code)

Clean up css (delete commented out code)
